services:
  db:
    image: postgres:18.3
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - TZ=Asia/Tokyo
    tmpfs:
      - /var/lib/postgresql
    networks:
      - security-nw

networks:
  security-nw: