spring:
  application:
    name: security-sample
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    locations: classpath:/db/migrations
    schemas: auth
    default-schema: auth

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    root: info
    org.springframework.security: debug
#  structured:
#    format:
#      console: ecs